<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="tests.technix.TechnixTests-20220523142955" tests="6" file="tests/technix.py" time="17.968" timestamp="2022-05-23T14:30:20" failures="1" errors="0" skipped="0">
	<testcase classname="tests.technix.TechnixTests" name="test_WHEN_set_inhibit_to_active_THEN_inhibit_is_active" time="1.131" timestamp="2022-05-23T14:30:11" file="tests\technix.py" line="78"/>
	<testcase classname="tests.technix.TechnixTests" name="test_WHEN_set_inhibit_to_idle_THEN_inhibit_is_idle" time="1.062" timestamp="2022-05-23T14:30:12" file="tests\technix.py" line="73"/>
	<testcase classname="tests.technix.TechnixTests" name="test_WHEN_set_local_mode_THEN_mode_is_local" time="1.124" timestamp="2022-05-23T14:30:14" file="tests\technix.py" line="63"/>
	<testcase classname="tests.technix.TechnixTests" name="test_WHEN_set_remote_mode_THEN_mode_is_remote" time="1.058" timestamp="2022-05-23T14:30:15" file="tests\technix.py" line="68"/>
	<testcase classname="tests.technix.TechnixTests" name="test_WHEN_set_voltage_THEN_get_voltage_back_correctly" time="5.312" timestamp="2022-05-23T14:30:20" file="tests\technix.py" line="47"/>
	<testcase classname="tests.technix.TechnixTests" name="test_WHEN_set_current_THEN_get_current_back_correctly" time="8.281" timestamp="2022-05-23T14:30:10" file="tests\technix.py" line="55">
		<failure type="AssertionError" message="Expected PV 'TE:NDW1799:TECHNIX_01:CURRENT' value to be equal to '10.0' (type: 'float') (tolerance: '0.0' (type: 'float'))
Final PV value was '9.99999' (type: 'float')"><![CDATA[Traceback (most recent call last):
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\testing.py", line 148, in wrapper
    return func(*args, **kwargs)
  File "C:\Instrument\Apps\EPICS\support\technix\master\system_tests\tests\technix.py", line 59, in test_WHEN_set_current_THEN_get_current_back_correctly
    self.ca.assert_that_pv_is_number("CURRENT", max_curr)
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 380, in assert_that_pv_is_number
    return self.assert_that_pv_value_causes_func_to_return_true(
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 248, in assert_that_pv_value_causes_func_to_return_true
    raise AssertionError(err)
AssertionError: Expected PV 'TE:NDW1799:TECHNIX_01:CURRENT' value to be equal to '10.0' (type: 'float') (tolerance: '0.0' (type: 'float'))
Final PV value was '9.99999' (type: 'float')
]]></failure>
	</testcase>
</testsuite>
